### ISSUE TITLE
Fix script for automating compilation

### ISSUE THREAD

**Issue by datum-dpoulin** [Datum-Technology-Corporation/core-v-mcu-uvm#1]
mio is not currently running fsoc properly:

```
$ mio all uvmt_cvmcu -t smoke -s 1
********
Cleaning
********
Invoking FuseSoC: ip='core-v-mcu' target='sim' + full-name='openhwgroup.org:systems:core-v-mcu'
Traceback (most recent call last):
  File "/home/mike/GitHubRepos/Datum-Technology-Corporation/core-v-mcu-uvm/main/sim/../tools/.imports/mio/src/__main__.py", line 157, in <module>
    do_dispatch(args)
  File "/home/mike/GitHubRepos/Datum-Technology-Corporation/core-v-mcu-uvm/main/sim/../tools/.imports/mio/src/__main__.py", line 137, in do_dispatch
    cmp.cmp_rtl(args['<target>'])
  File "/home/mike/GitHubRepos/Datum-Technology-Corporation/core-v-mcu-uvm/main/tools/.imports/mio/src/cmp.py", line 136, in cmp_rtl
    fusesoc.main.run(fsc_cm, fsc_args)
  File "/home/mike/.local/lib/python3.8/site-packages/fusesoc/main.py", line 412, in run
    args.verbose,
AttributeError: 'Namespace' object has no attribute 'verbose'
$ 
```

**Comment by datum-dpoulin** [comment]
@MikeOpenHWGroup can you please confirm your fusesoc version? I'm using 1.12.0

**Comment by datum-dpoulin** [comment]
Turns out the latest stable version of fsoc is compatible with the current state of the 'xilinx-support' branch. Adding python library reqs to readme
